#.github/workflows/main.yml
name: Scratch org for review
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: pwd
      run: |
        pwd
        ls -l
        cd ..
        ls -l
        pwd
        cd ..
        ls -l
        pwd
        cd..
        ls
        
        
        
        
    - name: dir
      run: ls
    - name: cd
      run: cd ../../
    - name: pwd
      run: pwd
    - name: dir
      run: ls
      
      
