#.github/workflows/main.yml
name: Scratch org for review
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: pwd
      run: pwd
    - name: dir
      run: dir
    - name: cd
      run: cd /home/runner/work
    - name: pwd
      run: pwd
    - name: dir
      run: dir
      
      
