name: 'sfdx'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2            
      - name: Write the token into a file
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > server3.key'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Current Rirectory
        run: pwd
      - name: List
        run: dir
      - name: Auth with the DevHub
        run: 'sfdx force:auth:logout --targetusername akshay@ibmpune.com -p & sfdx force:auth:jwt:grant --clientid 3MVG9pe2TCoA1Pf58FPkW972jDpNE5zEui_PbFdTjIanHrQoq72R4hY_mFG7BbG6SftXK4gLgloytBOOMgUIZ  --jwtkeyfile server3.key --username akshay@ibmpune.com -a myConnectedOrg'
      - name: Create scratch org
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a my-scratch'
      - name: Push source
        run: 'sfdx force:source:push -u my-scratch'
      - name: List orgs
        run: 'sfdx force:org:list'
      - name: Run tests
        run: 'sfdx force:apex:test:run -u my-scratch --resultformat human'
      - name: Delete scratch org
        run: 'sfdx force:org:delete -u my-scratch --noprompt'
