name: 'sfdx'
 
on: [push] 
 
jobs:
  build:

   runs-on: ubuntu-latest

    steps:
     #
# Download the Salesforce CLI and install it
#
before_script:
 
# Set up environment variables
  - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz  
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - export DEPLOYDIR=salesforce/Src/force-app
   

#Create sfdx directory
  - mkdir sfdx
  
#Install Salesforce CLI 
  - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
  - "sudo ./sfdx/install"
# Output CLI version and plug-in information
  - /usr/local/bin/sfdx update
  - /usr/local/bin/sfdx --version
  - /usr/local/bin/sfdx plugins --core

# Create tmp folders
  - mkdir tmp-force-app
  - mkdir force-app
